### ISSUE TITLE
No longer able to set automation to run every 5min?

### ISSUE THREAD

**Issue by threeonparfive** [clickbg/homekit-monitord#14]
I know it's been a while since this was updated but have just stumbled upon this and was hoping to make use.  Unfortunately, it appears as though it's no longer possible to set the required automation shortcut to run every 5min.  I've tried Controller and Eve and neither seem to give that option any longer.  Can you confirm and do you have an alternate solution perhaps?

**Comment by clickbg** [comment]
Hi! 

Yes it still works and I try to update the container regularly at least for security fixes. So Apple moved the things a bit with iOS 18. You have to do it in reverse - create the automation in Controller first, set some Scene (no matter which) and make it executable every 5 minutes (In recurring time periods) save the automation and go back to Apple Home, edit the new automation and convert it to shortcut by clicking on "Select Accessories and Scenes..." then going down to the end of the page and click the "Convert to Shortcut" button. Set the URL and actions as described in the README here and save the automation. It should still execute every 5 minutes.

I will update the documentation here in the coming days when I have a bit of time to take new screenshots as both Apple Home and Controller changed a bit in the past year.

**Comment by threeonparfive** [comment]
Thanks for getting back to me!  This approach sounds way better than the workaround path I was on.  Luckily, I have only managed to go through 13 hours worth of creating run times on 5min intervals.  Yeah....been a slow day at work.  Nice to know that I don't have to finish that mess.
